//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tabula
{
    [Serializable]
    public class AvailableEntitiesMsg : Message
    {
        public const string k_RosMessageName = "tabula_msgs/AvailableEntities";
        public override string RosMessageName => k_RosMessageName;

        public EntityMsg[] entities;

        public AvailableEntitiesMsg()
        {
            this.entities = new EntityMsg[0];
        }

        public AvailableEntitiesMsg(EntityMsg[] entities)
        {
            this.entities = entities;
        }

        public static AvailableEntitiesMsg Deserialize(MessageDeserializer deserializer) => new AvailableEntitiesMsg(deserializer);

        private AvailableEntitiesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.entities, EntityMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.entities);
            serializer.Write(this.entities);
        }

        public override string ToString()
        {
            return "AvailableEntitiesMsg: " +
            "\nentities: " + System.String.Join(", ", entities.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
