//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Tabula
{
    [Serializable]
    public class UpdateMsg : Message
    {
        public const string k_RosMessageName = "tabula_msgs/Update";
        public override string RosMessageName => k_RosMessageName;

        public int msg_id;
        public int type;
        public string update;

        public UpdateMsg()
        {
            this.msg_id = 0;
            this.type = 0;
            this.update = "";
        }

        public UpdateMsg(int msg_id, int type, string update)
        {
            this.msg_id = msg_id;
            this.type = type;
            this.update = update;
        }

        public static UpdateMsg Deserialize(MessageDeserializer deserializer) => new UpdateMsg(deserializer);

        private UpdateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.msg_id);
            deserializer.Read(out this.type);
            deserializer.Read(out this.update);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.msg_id);
            serializer.Write(this.type);
            serializer.Write(this.update);
        }

        public override string ToString()
        {
            return "UpdateMsg: " +
            "\nmsg_id: " + msg_id.ToString() +
            "\ntype: " + type.ToString() +
            "\nupdate: " + update.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
